# Generated by Django 5.0.3 on 2024-03-19 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20240315_0302'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                (
                    """
                    ALTER TABLE bill DROP COLUMN IF EXISTS participant_owes_id;
                    """
                ),
            ],
            reverse_sql=[
                (
                    """
                    ALTER TABLE bill
                    ADD COLUMN IF NOT EXISTS participant_owes_id INTEGER,
                    ADD CONSTRAINT fk_owes_participant FOREIGN KEY (participant_owes_id) REFERENCES participant(participant_id);
                    """
                )
            ]
        )
    ]
