# Generated by Django 5.0.3 on 2024-03-21 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20240319_2311'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                (
                    """
                    ALTER table transaction ADD COLUMN amount DECIMAL(10,2);
                    """
                ),
            ],
            reverse_sql=[
                (
                    """
                    ALTER table transaction DROP COLUMN if exists amount;
                    """
                )
            ]
        )
    ]
